# Generated by Django 3.1.4 on 2021-02-10 19:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderidmerge',
            name='dtime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
