# Generated by Django 3.1.4 on 2021-02-19 04:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210211_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderidmerge',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 4, 16, 39, 614944, tzinfo=utc)),
        ),
    ]
