# Generated by Django 3.1.4 on 2021-02-19 04:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20210219_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderidmerge',
            name='dtime',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 19, 9, 48, 19, 155967)),
        ),
    ]
